### PR TITLE
Initial commit, updated responsiveness

### PR DESCRIPTION
**Pull request by KMDOFNI**
Ircommission

### CODE REVIEW

**Review by omahm — CHANGES_REQUESTED** [review]
Looks mostly ok but I'd look at giving the likes of View ID's some context: 'id: views_block__irc_key_documents_views_block_2' doesn't give me much idea beyond being something around irc key documents..

**Review by DuttonMa — CHANGES_REQUESTED** [review]
Lots of files in this change, and in fact I think there are too many !
I see that you have changed files in project/config/publicappointmentsni which I think should be removed from this PR as you are not working on this site.
There are also files in these directories that should be removed:
sites/mentalhealthchampionni
sites/publicappointmentsni

**Comment by soda736** [comment]
Looks like this PR has been made against the main branch and not development. Maybe change the PR to development and there will be a lot less files.

**Review by DuttonMa — APPROVED** [review]
Looks good now

**Review by omahm — APPROVED** [review]

**Pull request merged**
